name: Build and Push to Artifactory

on: 
  push:
    branches: 
      - master
      
jobs:
  maven_nexus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: debug
        run: ls
      
      - name: Set up JDK
        uses: actions/setup-java@v1
        with: 
          java-version: '1.8'
          
      - name: debug
        run: ls          
          
      - name: Build Maven
        run: mvn package --file pom.xml
        
      - name: debug
        run: ls ./target        
        
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://35.158.97.201:8081
          username: admin
          password: ${{ secrets.password }}
          format: maven2
          repository: maven-public
          coordinates: groupId=flipkart artifactId=maven-app version=1.0.0
          assets: extension=jar
          filename: ./target/maven-app-1.0.0.jar
